### ISSUE TITLE
Please fix the file header

### ISSUE THREAD

**Issue by nullman** [daniel-ness/ini.el#3]
Please change the file header to conform to the standard described here:  https://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html

Basically just use three semicolons instead of five.

~I'll try to submit a PR for this change.~  [UPDATE:  I don't seem to have permissions to do this.]

This would allow the following code to work:

```
(use-package ini
  :quelpa (ini :fetcher github :repo "daniel-ness/ini.el"))
```

[UPDATE 2]

After playing with a local copy of your file, it looks like this comment at the EOF is also needed:

```
;;; ini.el ends here
```

**Comment by daniel-ness** [comment]
Hey @nullman 

Updated as requested, can you try now?

**Comment by nullman** [comment]
Works great for me.  Thanks Daniel!
